apiVersion: v1
kind: Service
metadata:
  name: student-svc
  namespace: student
spec:
  selector:
    app: student-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
