replicaCount: 2

image:
  repository: ghcr.io/atuan0354/student-management
  tag: "7"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: vtisa03.com.vn
  path: /

envSecret: db-secret
